version: '2'
services:
    funpile-app:
        image: funpile
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_COUCHBASE_BOOTSTRAP_HOSTS=funpile-couchbase
            - SPRING_COUCHBASE_BUCKET_NAME=FunPile
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    funpile-couchbase:
        extends:
            file: couchbase.yml
            service: funpile-couchbase
